[program:ump-queue]
process_name=%(program_name)s_%(process_num)02d
command=php /var/www/ump/current/artisan queue:work redis --sleep=3 --tries=3 --timeout=90
autostart=true
autorestart=true
numprocs=1
user=www-data
redirect_stderr=true
stdout_logfile=/var/www/ump/shared/storage/logs/queue-worker.log
stopwaitsecs=3600
